### ISSUE TITLE
How opening the current image on other pages in paging?

### ISSUE THREAD

**Issue by ThiagoJem** [compact/angular-bootstrap-lightbox#10]
Images that are not on the home page (index) will not open . How to configure to display the current image that are on other pages in the paging ?

Thank you!

**Comment by compact** [comment]
It looks like you are using `$index` as in `Lightbox.openModal(images, $index)`, but each page in the pagination starts it over at 0, so `$index` goes `0, 1, 0, 1, 0, 1...` instead of `0, 1, 2, 3, 4, 5...`

I found a relevant answer in that library: https://github.com/michaelbromley/angularUtils/issues/76

Add this to your controller:

```js
$scope.imageIndex = $scope.$index + ($scope.currentPage - 1) * $scope.pageSize;
```

Then change your `$index` to `imageIndex`.

**Comment by ThiagoJem** [comment]
It did not work.
I thought better and I will make content open on another page , I will most benefit and ease in other implementations. Valeu, abraço!
