### ISSUE TITLE
Modal Background Not closing

### ISSUE THREAD

**Issue by engemasa** [compact/angular-bootstrap-lightbox#21]
The background/overlay does not hide when I close the dialogue box (either clicking off or clicking the "close" button).

**Comment by compact** [comment]
In which browser and device?
In the demo, or in your own installation (with which versions of Bootstrap and UI Bootstrap)?

**Comment by engemasa** [comment]
Sorry for the delayed response. This is in my own installation.
Google Chrome (Both Mac OS and Windows platforms)
Here's the dependencies I have:
* "angular": "^1.3.0",
* "bootstrap": "^3.2.0",
* "angular-animate": "^1.3.0",
* "angular-cookies": "^1.3.0",
* "angular-resource": "^1.3.0",
* "angular-sanitize": "^1.3.0",
* "angular-touch": "^1.3.0",
* "angular-bootstrap": "~0.13.0",
* "angular-ui-router": "~0.2.15",
* "components-font-awesome": "~4.3.0",
* "angular-ui-utils": "bower-mask",
* "angular-spinner": "~0.6.1",
* "angular-bootstrap-lightbox": "~0.6.1",
* "angular-loading-bar": "~0.7.1"

**Comment by glothriel** [comment]
I have the same issue

**Comment by compact** [comment]
Since you are using ngAnimate, the problem appears to be a breaking change with 1.4, which UI Bootstrap does not support yet: https://github.com/angular-ui/bootstrap/issues/3633

I can reproduce the issue by adding ngAnimate as a dependency. The backdrop works properly again when I downgrade all the Angular packages from 1.4.1 to 1.3.16. Another option for now is to remove the ngAnimate dependency if you are not using it directly.

**Comment by engemasa** [comment]
Thank you, this is working now.
